### ISSUE TITLE
Conda environment

### ISSUE THREAD

**Issue by t-whalley** [xiaoyeye/CNNC#17]
Hi, seeing as you recommend using conda to manage the environment would it be possible to share your environment.yml file or the output from ```conda list```  as I am having some trouble finding the right combination of packages.

Thanks

**Comment by t-whalley** [comment]
Apologies, literally the first attempt after posting this worked, despite lots of failed attempts before!

my environment.yml is below in case anyone else has similar problems:

```
name: cnnc
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - tensorflow=2.1.0
  - keras
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - h5py=2.10
```

**Comment by xiaoyeye** [comment]
Thanks.
